src/pages/visualizations/[visualizationId].tsx, src/pages/visualizations/index.tsx, src/visualizations/__tests__/__snapshots__/visualizations.test.tsx.snap
This PR fix the displayed name on the breadcrumb and the redirect url.
- Displayed name on breadcrumb
- Href for the link
Check the breadcrumb is correctly set.
=> fix(Visualizations): fix breadcrumb text and redirect url

src/pipelines/features/RunMessages/RunMessages.tsx
Fix issue about DAG run messages not entirely displayed.
- Add pagination to messages section
Select a DAG Run, open a Run details page and view the messages section if it display all messages.
=> fix(Pipelines): add pagination on dag run messages table

src/pipelines/features/PipelineRunDataCard/PipelineRunDataCard.tsx
Re-run job action should only be displayed when the run is either failed or succeded.
1. Trigger a pipeline run.
2. "Re-run job" should not be visible
3. When job is done, "re-run" is displayed
=> fix(PipelinesRun): Only display re-run action when job is finished

src/core/components/Layout/Header.tsx, src/core/components/Menu.tsx
Fix https://github.com/BLSQ/openhexa-team/issues/92 
- add linkTo props to MenuItem component
Click on the user menu dropdown and check if the items can be opened in a new tab.
=> fix(HeaderMenu) : render menuItem as anchor or button

src/pipelines/features/PipelineRunForm/GenericForm.tsx
Display the error below the configuration field
Type an invalid json in the configuration of a pipeline
=> fix(Pipelines): Display an error when user types an invalid json configuration

src/core/components/Menu.tsx
The menu in the header does close itself automatically on click of an element inside.
We have to return a real component for the button
Open the menu and click on "account". The menu should closes itself automatically.
=> Fix header menu

public/locales/en/messages.json, public/locales/fr/messages.json, src/pages/workspaces/index.tsx
Fix for https://github.com/orgs/BLSQ/projects/4/views/2?filterQuery=label%3Abug&pane=issue&itemId=18245334
- Check if user can create workspace on client-side if he didn't have one.
- Change 2
=> fix(Workspaces):display warning when user can't create workspace

src/core/components/DataCard/FormSection.tsx, src/pages/pipelines/[pipelineId]/index.tsx
Move `id` & `schedule` In the first block.
Collapse  "Airflow Data" by default
=> fix(Pipelines): Move fields from Airflow data & collapse it by default

src/core/components/DataCard/FormSection.tsx, src/core/helpers/apollo.ts, src/pages/pipelines/[pipelineId]/index.tsx, src/workspaces/helpers/connection.tsx
Since we do not use the workspace id on the frontend anymore, we have to set the identifier field in Apollo to be able to store the data in the cache
Python snippet for custom connection was incorrect
=> Fix workspace connection

src/pages/workspaces/[workspaceSlug]/settings.tsx
User that belongs to a workspace and didn't have the  admin role for the workspace can access to the settings page by typing /workspaces/[slug]/settings.
- Redirect to home page if  current user  doesn't have permission to manage a workspace.
Create/Use a no workspace admin and try to access to /workspaces/[slug]/settings (should be redirected to /workspaces)
=> fix(Workspaces) : allow only workspace admins to access settings page

src/pages/pipelines/[pipelineId]/index.tsx, src/pages/pipelines/[pipelineId]/runs/[runId].tsx, src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineId]/index.tsx, src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineId]/run.tsx, src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineId]/runs/[runId].tsx
Returns an 404 if the pipelines or its runs used in the workspaces as mocks do not exist
=> fix(workspaces): Return a 404 if the mock pipeline or run does not exist

src/pages/workspaces/[workspaceSlug]/notebooks.tsx, src/workspaces/__tests__/__snapshots__/workspaces.test.tsx.snap, src/workspaces/__tests__/workspaces.test.tsx, src/workspaces/graphql/queries.generated.tsx, src/workspaces/graphql/queries.graphql, src/workspaces/layouts/WorkspaceLayout/Sidebar.tsx
Hide JupyterHub menu entry on the sidebar for user with role VIEWER.
- Hide menu entry
- Return not found when user try to access to /notebooks
Create a Workspace Member with Role Viewer, connect with it and check that the JupyterHub menu entry is hidden and  try to access to /notebooks.
=> feat(Workspaces): hide notebooks menu entry for user with role VIEWER

src/workspaces/features/SidebarMenu/SidebarMenu.tsx
Hide link to  Administration page for non admin/staff user.
- check on user permissions instead of features.
=> fix(Workspaces): hide administration link for non admin/staff user

src/workspaces/features/CreatePipelineDialog/CreatePipelineDialog.tsx
If the workspace' slug was too long, it was cropped and not wrapped to the second line.
=> fix(Pipelines): Break long workspace slug in CreatePipelineDialog

src/core/helpers/page.ts
Fix for [issue](https://github.com/BLSQ/openhexa-team/issues/381) .
- Check if user has workspaces feature before redirection.
Create a user with only openhexa_legacy  feature  and try to access to a workspace, you should be redirected to home page.
=> fix(Workspaces): allow access to only users with workspaces feature

src/workspaces/features/WorkspaceMembers/WorkspaceMembers.tsx
Prevent admin from updating/deleting his membership
- Hide update/delete buttons for connected user membership
Go to settings page and try to see it's possible to edit your role or delete your membership.
=> fix(Workspaces): prevent admin from updating/deleting his membership

src/pages/workspaces/[workspaceSlug]/connections/[connectionId].tsx, src/pages/workspaces/[workspaceSlug]/databases/index.tsx, src/workspaces/features/DatabaseVariablesSection/DatabaseVariablesSection.tsx, src/workspaces/features/DatabaseVariablesSection/SecretField.tsx, src/workspaces/graphql/queries.generated.tsx, src/workspaces/graphql/queries.graphql
Hide connections/database parameters  sections for viewer.
- Check if user is editor or admin (editor and admin have update permission on workspace)/
Log into a workspace as a viewer, go to the database page and check that locked icons are displayed for each parameter.
Database
Connection
=> feat(Workspaces): hide connections/database parameters  for viewers

src/workspaces/features/PipelineCard/PipelineCard.tsx
Fix glitch on pipelines list views.
- Set pipeline card title  width at 80%
Create/edit a pipeline with a long title and check if the pipeline status is correctly displayed.
=> fix(Pipelines): set pipeline card title to 80%

src/workspaces/features/SidebarMenu/SidebarMenu.tsx
Restrict workspace creation to super user.
-  Display add button only for superuser
Connect with a non super user, the add button on the sidebar should be hidden.
=> feat(Workspaces): restrict workspace creation to superuser

src/workspaces/features/CreatePipelineDialog/CreatePipelineDialog.tsx
We were still using the old HOWTO guide in the link in the pipeline create modal.
- Replaced old howto by new wiki link
=> fix(Pipelines): fix guide URL

src/core/helpers/apollo.ts
By default, the first query on client side will try to take it from the cache and not fetch from the server (it works because we preload the data on the server)
But if we try to useQuery again after the first client side call, we use the `nextFetchPolicy` "cache-and-network" to display directly what's in the cache while we fetch the new results from the server
=> fix(Apollo): Set next fetch policy to "cache-and-network"

sentry.client.config.js, sentry.server.config.js, src/core/components/ErrorBoundary/ErrorBoundary.tsx, src/core/components/ErrorBoundary/index.ts, src/pages/_app.tsx
+ configure the tracing to not try to send the Baggage header to the api
The goal is to avoid to have <unlabeled event> in Sentry
There is a new error page when there is a bug in the client code.
=> fix(Sentry): Add an ErrorBoundary wrapping nextjs app

src/workspaces/features/RunPipelineDialog/ParameterField.tsx
This PR intentds to fix  [issue](https://github.com/BLSQ/openhexa-team/issues/405) about broken search on parameter of type int/float that accept choices.
- Parse options to string
Open the dialog for running a pipeline with a parameter of type int/float that accept choices and try to search on the displayed select.
=> fix(Pipelines): parse float/int parameter to string for select

server/index.mjs, src/pages/workspaces/[workspaceSlug]/notebooks.tsx
The `__next` prefix is necessary to let Nextjs replies to the requests when an error occurred in development (until now, it was forwarded to the backend that has no clue on what to do with this)
=> chore: Remove console.log & fix erorr in dev mode

src/workspaces/helpers/connection.tsx
Nothing special, just a label change (Google GCS bucket instead of Google Cloud Bucket).
=> chore(Connections): change label for GCS buckets

src/pipelines/features/PipelineRunStatusBadge.generated.tsx, src/pipelines/features/PipelineRunStatusBadge.tsx, src/pipelines/hooks/usePipelineRunPoller/index.ts, src/pipelines/hooks/usePipelineRunPoller/usePipelineRunPoller.generated.tsx, src/pipelines/hooks/usePipelineRunPoller/usePipelineRunPoller.test.tsx, src/pipelines/hooks/usePipelineRunPoller/usePipelineRunPoller.ts, src/workspaces/features/PipelineCard/PipelineCard.generated.tsx, src/workspaces/graphql/queries.generated.tsx
It polls each pipeline run when it's in queued or running.
The hook is for the moment only used in `PipelineRunStatusBadge`
=> fix(Run): Poll the status of the run if it's queued or in progress

src/core/components/forms/Combobox/Combobox.tsx, src/core/components/forms/Combobox/MultiCombobox.tsx, src/core/components/forms/Select.tsx, src/workspaces/features/RunPipelineDialog/ParameterField.tsx
Fix for [issue](https://github.com/BLSQ/openhexa-team/issues/440). This issue is related to the default comparator function used by the ComboBox component.
- Allow user defined function in  MultiCombobox/combobox props
Use a pipeline with int/float parameter with choices and check that a selected element is highlighted.
[Screencast from 21.06.2023 10:25:23.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/82f3cc40-e82f-4feb-8ef6-fe552cba368e)
=> fix(Pipelines): add comparator function for parameters with choices

public/locales/en/messages.json, public/locales/fr/messages.json, src/workspaces/features/UploadObjectDialog/UploadObjectDialog.generated.tsx, src/workspaces/features/UploadObjectDialog/UploadObjectDialog.tsx
It was confusing for users to see the target directory when they upload files through the interface.
- I removed the display of the path in the dialog
=> fix(Files): Do not display the target directory

public/locales/en/messages.json, public/locales/fr/messages.json, src/workspaces/features/RunPipelineDialog/RunPipelineDialog.test.tsx, src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
The SDK set all parameters are required by default. That's a state we do not want for the bool parameters (it would force the users to put them at true in the UI)
=> fix(RunPipeline): Bool parameters are never required

src/workspaces/helpers/bucket.ts
When users wanted to download files, some triggered a the browser to download the object directly while other opened a new windows with the content of the file. 
We changed this behaviour (mainly) on openhexa-app:  https://github.com/BLSQ/openhexa-app/pull/490
=> fix(Files): The download of an object happens with a content-disposition:download

src/workspaces/features/SidebarMenu/SidebarMenu.tsx
- Display the active workspace
- Add a globe icon in front of workspaces without or with more than one country
- Clean up the code
=> chore(Sidebar): Visual improvements on how we display the workspaces

public/locales/en/messages.json, public/locales/fr/messages.json, schema.graphql, src/graphql-types.ts, src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx, src/workspaces/graphql/queries.generated.tsx, src/workspaces/graphql/queries.graphql
- display schedule section only when the pipelines has no parameters.
Pipeline without parameters
Pipeline with parameters
=> fix(Pipelines): allow scheduling for only pipelines without parameters

public/locales/en/messages.json, public/locales/fr/messages.json, src/pages/workspaces/[workspaceSlug]/connections/index.tsx, src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx, src/workspaces/graphql/queries.generated.tsx, src/workspaces/graphql/queries.graphql
The permission has been changed : update -> createConnection
Use an editor account and go to the connections page. The "create connection" should not be visible
=> fix(Connections): Wrong permission was checked to display the create a connection dialog

src/pages/workspaces/[workspaceSlug]/connections/[connectionId].tsx, src/pages/workspaces/[workspaceSlug]/connections/index.tsx, src/workspaces/__tests__/connections.test.tsx
Permissions fixes for the connection.
- Do not display the "Add connection" to non-admins
- Do not allow non-admins to edit connections
- Display the connection fields to all workspace members
=> fix(Connections): Hide 'add connection' button for non-admins

src/workspaces/__tests__/__snapshots__/workspaces.test.tsx.snap, src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
The header of the workspace layout was not sticky anymore.
I was able to remove a few useless classes as well
=> fix(Layout): Header was not sticky, make css simpler

src/core/components/DataCard/__tests__/__snapshots__/DataCard.test.tsx.snap, src/core/components/DescriptionList/DescriptionList.tsx, src/core/components/DescriptionList/__snapshots__/DescriptionList.test.tsx.snap, src/visualizations/__tests__/__snapshots__/visualizations.test.tsx.snap
Align the label of the description list vertically
=> fix: Align vertically the label in description list

jest.setup.js, package-lock.json, package.json
Resolve  failing tests for #457 . 
- Change router-context import path on jest.setup.js (module location has changed in next 13.5.5)
=> chore(deps)(deps): bump next from 13.4.4 to 13.5.5

src/workspaces/features/RunPipelineDialog/ParameterField.test.tsx, src/workspaces/features/RunPipelineDialog/ParameterField.tsx
Fix for https://github.com/BLSQ/openhexa-team/issues/594.
- Check if parameter is multiple and doesn't have choices
- Use empty array as default when parameter default choice is not defined.
Create a pipeline with a parameter of type int/float, multiple and have choices.
[Screencast from 10-25-2023 03:46:52 PM.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/f5c9c301-8625-49f3-8076-5df8c0bf0881)
=> fix(Pipelines): Fix issues on multiple choice param

src/workspaces/features/RunPipelineDialog/ParameterField.tsx, src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx, src/workspaces/features/WorkspaceConnectionPicker/WorkspaceConnectionPicker.test.tsx, src/workspaces/features/WorkspaceConnectionPicker/WorkspaceConnectionPicker.tsx, src/workspaces/features/WorkspaceConnectionPicker/__snapshots__/WorkspaceConnectionPicker.test.tsx.snap, src/workspaces/helpers/pipelines.ts
Filter and display the correct connection from pipeline run config.
- Filter and display connection based on the value (if empty return null)
- Change WorkspaceConnectionPicker value type (from Option to string)
- Pass the connection slug to onChange method in ParameterField instead of connection object
[Screencast from 11-22-2023 12:53:39 PM.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/47053bc8-4288-4502-99c2-f92d7228f0ef)
=> fix(PipelineDialog): prevent display of empty value on picker

src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx
My latest change was to replace the empty string by null. It passes the null value to the server and boom.
=> fix(files): Replace the default value of query by an empty string

src/workspaces/features/RunPipelineDialog/RunPipelineDialog.test.tsx, src/workspaces/helpers/pipelines.ts
If the int or float parameter value was "" it would call `parseInt` and set the value as NaN.
=> fix(Pipelines): null & empty values for int and float should be ignored

src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
Otherwise the run again dialog refreshes the params values every second or so.
=> fix(Pipelines): Only display the 'run again' button for finished runs

src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx, src/workspaces/graphql/queries.generated.tsx, src/workspaces/graphql/queries.graphql
On the bucket explorer, a member with viewer role can interact with the create folder and upload files button, even though they cannot create/upload object, but an error will be show if they try to. (see https://github.com/BLSQ/openhexa-team/issues/714)
- Check if user has createObject permission on the workspace before showing Upload files/ Create folder buttons.
=> fix(Files): hide upload and create button for viewer

src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
On the frontend we only checked to see if the run.Outputs field has values  and that prevented the display of dataset versions on the outputs table.
- Merge run.outputs and run.datasetVersions
=> fix(PipelineRun): include dataset versions output to runOuputs

src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx
Searching for files in a workspace does not work on FF & Chrome. It works on dev with this fix but I think we'll have to wait to deploy it in demo to check that.
=> fix(Files): Search for files works on FF & Chrome

src/workspaces/__tests__/__snapshots__/workspaces.test.tsx.snap, src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
This can be tested on /files & /database pages
=> fix(Sidebar): In compact mode, the sidebar labels were under the tables

src/workspaces/features/CronProperty/CronProperty.tsx
On the CronProperty component the link to crontab.guru app is not correctly set when there's no cron expression to evaluate (it shows https://crontab.guru#undefined).
Changes  : 
- Add parenthesis to evaluate nullish coalescing operator before assigning.
=> fix(Workspaces): fix bar url on cron property

src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
When creating a custom connection if the user doesn't add fields, the following error is displayed :  _Cannot read properties of undefined (reading 'map')_ .
- Add a check on connection fields
- Change 2
=> fix(Connections): check if connection fields is defined

src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug].tsx
Use dataset slug for dataset identifier instead of id.
=> fix(Analytics): use slug for dataset_id properties

src/workspaces/features/UploadObjectDialog/UploadObjectDialog.tsx
Users do not know they can click on the upload box in the dialog to open a file picker
- Disable upload button until a file is selected.
- Reset form state when Dialog is closed
https://github.com/user-attachments/assets/91b36268-9333-4f01-a323-b834f984549c
=> feat(FileUploader): prevent user to inadvertently click on upload

src/core/helpers/apollo.ts
The nextFetchPolicy is taken from the Apollo documentation
We saw that when navigating between pages using links the Apollo cache was not used to render the data even though it was pre-populated by the SSR of the app. This was caused by the `cache-and-network` setting that always fires a request to the server to ensure to have the freshest data possible. It's not relevant for the initial load since we can be certain it is fresh.
`cache-and-network`
> Apollo Client executes the full query against both the cache and your GraphQL server. The query automatically updates if the result of the server-side query modifies cached fields.Provides a fast response while also helping to keep cached data consistent with server data.
=> fix(Apollo): Set initialFetchPolicy to 'cache-first' and implement a basic nextFetchPolicy

src/datasets/features/DatasetVersionFileColumns/DatasetVersionFileColumns.tsx, src/datasets/helpers/dataset.ts
For previous profiled datasetFile the count attribute was not available and the percentage computation was throwing an error in that case. Now, we return empty string when total count is not available.
- percentage helper return null when total is NaN or negative.
Open an old dataset file columns section, the percentage for the stats should be not displayed if not available.
=> fix(Datasets): do not throw when column total values is not available

src/core/components/Listbox/Listbox.tsx, src/core/hooks/useIntersectionObserver.ts, src/datasets/features/DatasetVersionPicker/DatasetVersionPicker.test.tsx
When scrolling on dataset versions only 10 are showing while we expect additional to reload
This is due to https://github.com/BLSQ/openhexa-frontend/pull/902 -> the upgrade made the options invisible in the DOM so the ref tracking the last element was null
- Ensure the ref to the last element is non null by setting it in a component in the dropdown view
- A unit test to cover the fetching of that 
The dataset dropdown fetches data as we scroll
https://github.com/user-attachments/assets/52d32551-a889-4ec5-bfec-f88c62ee09fd
=> fix: HEXA-1153 scrolling dataset versions

src/core/components/DataGrid/DataGrid.tsx
Rendering Datagrids is causing error logs in dev because the key is part of the destruct props.
- Extract the key from the props and pass it independently
No more error logs for Datagrids
=> fix: HEXA-1147 props in Datagrid

src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx, src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
Related to issue [JIRA-1132](https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/330?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-1132).  The Sidebar was always open even if we collapsed it.
- Reset initial value for isSidebarOpen state (removed previously)
- Fix `cookieSidebarOpenState` that was changing value between server and client (see https://github.com/andreizanik/cookies-next?tab=readme-ov-file)
Collapse the sidebar, change or refresh page, and check if it keeps its state.
https://github.com/user-attachments/assets/52a774e8-7fe6-4c49-b3ae-0d6fd51e1f7a
=> fix: set default state for sidebar

src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
The width of the dialog has been deleted recently. It makes the dialog ugly when there are more than a few parameters
=> chore(Pipelines): Increase the width of the RunPipelineDialog

src/core/helpers/apollo.ts
PipelineParameters can not be merged in the Apollo cache because they don't have an `id`
Use the `code` as the `id`
Thanks @qgerome for the help on this one :)
=> fix: duplicates in cache (HEXA-1171)

src/core/helpers/page.ts
The backend has removed the `workspaces` feature flag. Let's adapt the frontend accordingly.
=> fix(Features): 'workspaces' FF has been removed

src/datasets/layouts/DatasetLayout.tsx, src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/access.tsx, src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/files/[[...fileId]].tsx, src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/index.tsx
When the sidebar is in "compact mode", a hard reload on the a dataset page throw an hydration error. The cause is the lack of data fetched on the server that brings differences between the dom on the server & the client.
- Put the sidebar in compact mode, reload the index page of a dataset in dev. No error should be thrown
=> fix(React): fix hydration error because the WorkspaceLayout (& thus Sidebar) was not loaded in the DatasetLayout pages

src/workspaces/features/CreatePipelineDialog/CreatePipelineDialog.tsx
The selected tab is reset but not the state of the component, causing a visual glitch when the template pipeline feature is enabled
- Wire the selected tab
=> fix: Glitch when opening, choosing a tab and then closing the pipeline create dialog with feature flag enabled

public/locales/en/messages.json, public/locales/fr/messages.json, schema.graphql, src/graphql/types.ts, src/pipelines/features/PublishPipelineDialog/PublishPipelineDialog.tsx
Cast duplicate error and show a message
=> fix: handle gracefully duplicate template name (HEXA-1199)

src/workspaces/layouts/WorkspaceLayout/Sidebar.test.tsx, src/workspaces/layouts/WorkspaceLayout/Sidebar.tsx
Refactor the `NavItem` to accept a `isCurrent` prop and moving the `isCurrent` logic into the parent
- Refactor
- 2 unit tests to cover the edge cases
Navigating the website correctly shows the active navigation item
=> fix: the sidebar pipelines tab is not marked as active when the user is in the templates pages (HEXA-1189)

src/core/components/DataCard/FormSection.tsx, src/core/components/DataCard/__tests__/__snapshots__/DataCard.test.tsx.snap
The dataset button is positioned using absolute but no z-index is specified, resulting in it rendered behind the description text and not clickable.
- Add a z-index (I have tried to render it without an absolute to avoid usage of z-index but it takes unnecessary space so I fell back to z-index)
Editing the dataset general section is possible
=> fix: Cannot edit dataset metadata (absolute button without z index) (HEXA-1210)

.github/workflows/release-please.yml, README.md
Until now it was a manual task to release a hot fix on the previous version.
This PR addresses that by running release-please on release/* branches. The rest stays the same.
=> chore(releases): release-please also run on release/* branches

src/core/components/MarkdownEditor/MarkdownEditor.tsx
There is truncation happening in the home page descriptions
This is due to backticks (`) being escaped by MxEditor
- I tried different plugins/configuration but without success
- So I felt back to removing the escaped characters
MxEditor is supporting inline code (`) and code blocks (```)
=> fix: markdown truncated after widget implementation (HEXA-1220)
