BLSQ/openhexa-frontend

- src/core/helpers/apollo.ts
- src/pages/_app.tsx
Needs https://github.com/BLSQ/openhexa-app/pull/318 in prod before being deployed
> Graphql endpoint

- src/pages/collections/[collectionId].tsx
> fix(Collections): Summary was erased on update of the description

- next-i18next.config.js
- public/locales/en/messages.json
- public/locales/fr/messages.json
- schema.graphql
- src/core/components/Layout/Header.tsx
- src/core/components/Layout/Layout.tsx
- src/core/components/Layout/Navbar.tsx
- src/graphql-types.ts
- src/identity/graphql/queries.generated.tsx
- src/identity/graphql/queries.graphql
- src/identity/hooks/useFeature.ts
- src/identity/hooks/useMe.tsx
- src/pages/_app.tsx
Used by now to hide/display collections in the menu
> feat(Features): Add features to schema

- src/pages/catalog/search.tsx
> fix(Search): Type select on search page is broken

- next-i18next.config.js
This is automatic when the browser asks for french
> fix(i18n): DO not redirect to /fr when requesting /

- src/pages/catalog/search.tsx
- src/pages/notebooks/index.tsx
Add missing title on Notebooks and Search Pages.
Open Notebooks/Search page and check if the title is present.
> fix(Title): add missing titles on search and notebooks page

- src/pipelines/features/RunLogs/RunLogs.tsx
Fix  issue about Dag Logs not fully .
- Display content
Open a Dag run and check if all content of  the logs section appear without being truncated.
> fix(Pipelines) : add scroll to dag run logs

- src/workspaces/helpers/fixtures.ts
add meaningful project names to workspaces fixtures
- Change 1
- Change 2
> feat(Workspaces) : add meaningful project names

- src/pipelines/features/PipelineRunForm/GenericForm.tsx
- src/pipelines/features/PipelineRunForm/IHPForm.tsx
Replace "Configure and run" by "Run" on the pipeline run screen (https://github.com/BLSQ/openhexa-team/issues/152).
- Replace Pipeline form button label 
> Replace label on pipeline run form

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/core/components/Card/CardContent.tsx
- src/pages/workspaces/[workspaceId]/connections/index.tsx
- src/pages/workspaces/[workspaceId]/files/index.tsx
- src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
- src/workspaces/features/PipelineCard/PipelineCard.tsx
- src/workspaces/features/SidebarMenu/SidebarMenu.tsx
- src/workspaces/helpers/fixtures.ts
Replace some faker data with terms familiar to our users
> More realistic fixtures

- dependabot.yml
> chore: configure dependabot

- src/pages/login.tsx
> fix(2FA): Fix send new token on login page

- schema.graphql
- src/identity/features/EnableTwoFactorDialog/EnableTwoFactorDialog.test.tsx
- src/identity/features/EnableTwoFactorDialog/EnableTwoFactorDialog.tsx
- src/pages/user/account.tsx
> 2fa fix login

- server/index.mjs
Server do not proxy server pages
- Change 1
- Change 2
> fix(server): Do not proxy urls starting by '/'

- src/core/helpers/apollo.ts
> fix: Graphql extensions may not be provided

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/workspaces/helpers/connection.tsx
Remove instance field from dhsi2 connection form on workspace.
- Remove unused field instance
> fix(Workspaces) : remove field instance from dhsi2 form

- sentry.edge.config.js
- src/core/components/Time/Time.tsx
- src/pipelines/features/PipelineRunDataCard/PipelineRunDataCard.tsx
> Fix hydration

- public/locales/en/messages.json
- public/locales/fr/messages.json
- schema.graphql
- src/graphql-types.ts
- src/pages/workspaces/[workspaceSlug]/notebooks.tsx
- src/workspaces/graphql/mutations.generated.tsx
- src/workspaces/graphql/mutations.graphql
Allow workspace users to launch a Jupyter notebook. In case an error occured, an error message will be shown to the user.
- Add mutation to launch a Jupyter notebook;
Navigate to the JupyterHub section on a workspace and check that the notebook is launched. In case of error, a dialog with a message should be displayed.
> feat(Workspaces): Create Workspace Notebooks

- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineId]/index.tsx
- src/workspaces/features/BucketExplorer/BucketExplorer.tsx
The link on the first column of the runs on a pipeline page (in a workspace context) is invalid
> Fix pipeline link

- src/workspaces/features/CreateWorkspaceDialog/CreateWorkspaceDialog.test.tsx
- src/workspaces/features/CreateWorkspaceDialog/CreateWorkspaceDialog.tsx
> chore(Workspaces): Only accept a country when creating a workspace

- package-lock.json
- package.json
- src/core/hooks/useLocalStorage.ts
- src/pages/workspaces/index.tsx
- src/workspaces/graphql/queries.generated.tsx
- src/workspaces/graphql/queries.graphql
- src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
> Redirect the user to the last workspace seen

- src/pages/workspaces/index.tsx
> fix(Workspaces): last visited workspace may be empty OPENHEXA-Q1

- src/pages/workspaces/index.tsx
- src/workspaces/features/CreateWorkspaceDialog/CreateWorkspaceDialog.tsx
It's displayed when users create their first workspace
- Change 1
- Change 2
> fix(Workspaces): Do not display cancel button on /workpaces page

- src/workspaces/helpers/connection.tsx
> fix(Connections): add sqlAlchemy and R snippets

- src/workspaces/helpers/connection.tsx
Set user field label to username
> fix(Connection): change user field label

- src/pages/workspaces/[workspaceSlug]/connections/[connectionId].tsx
Use default size and color for delete button
> feat(Connections): use default size for delete button

- src/workspaces/helpers/database.tsx
Fix bad url in database usage snippets (`WORKSPACE_DATABASE_URL` instead of `WORKSPACE_DB_URL`)
> Fix(Database): fix bad url in database usage snippets

- package-lock.json
- package.json
- src/core/hooks/useLocalStorage.ts
- src/identity/graphql/queries.generated.tsx
- src/identity/graphql/queries.graphql
- src/pages/workspaces/[workspaceSlug]/connections/[connectionId].tsx
- src/pages/workspaces/[workspaceSlug]/connections/index.tsx
- src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
- src/pages/workspaces/[workspaceSlug]/databases/index.tsx
- src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx
- src/pages/workspaces/[workspaceSlug]/index.tsx
- src/pages/workspaces/[workspaceSlug]/notebooks.tsx
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
- src/pages/workspaces/[workspaceSlug]/pipelines/index.tsx
- src/pages/workspaces/[workspaceSlug]/settings.tsx
- src/workspaces/__tests__/__snapshots__/workspaces.test.tsx.snap
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
- src/workspaces/features/SidebarMenu/SidebarMenu.tsx
- src/workspaces/helpers/pipelines.ts
- src/workspaces/layouts/WorkspaceLayout/Header.tsx
- src/workspaces/layouts/WorkspaceLayout/Sidebar.tsx
- src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
User can minimise the sidebar using a button.
When the user goes to the notebooks, the sidebar is automatically minimised and get back to its previous state when the user leaves the page.
> Let the user be able to minimise the sidebar

- src/core/components/forms/Select.tsx
- src/workspaces/features/RunPipelineDialog/ParameterField.tsx
Change create by add when typing a string on run dialog
> feat(Pipelines): change create by add when typing a string on run dialog

- src/pages/catalog/search.tsx
Fix broken select and search on datasource select input.
- Add displayValue function
- Add filterOptions function
Open the search page and check that we can select and search  a datasource by name or type without errors.
> fix(Catalog): add displayValue function

- src/core/components/DataCard/PropertyDisplay.tsx
- src/core/components/Dialog.tsx
- src/pages/workspaces/[workspaceSlug]/settings.tsx
- src/workspaces/__tests__/__snapshots__/workspaces.test.tsx.snap
- src/workspaces/features/WorkspaceMembers/WorkspaceMembers.generated.tsx
- src/workspaces/features/WorkspaceMembers/WorkspaceMembers.tsx
- src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
> Lot of fixes

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/workspaces/features/RunPipelineDialog/ParameterField.tsx
Replace Select  by Textarea component in RunPipelineDialog.
- Use TextArea instead of Select in ParameterField component.
> Replace Select by Textarea component in RunPipelineDialog.

- src/workspaces/features/ConnectionFieldsSection/ConnectionFieldsSection.tsx
Remove copy to clipboard button on connection parameters table
> fix(Connections): remove copy to clipboard button

- src/workspaces/features/PipelineVersionsDialog/PipelineVersionsDialog.generated.tsx
- src/workspaces/features/PipelineVersionsDialog/PipelineVersionsDialog.tsx
Fix versions list modal scroll issue.
- Enable pagination on versions list
> fix(Pipelines): enable pagination on versions list

- src/workspaces/features/DeletePipelineVersionDialog/DeletePipelineVersionDialog.tsx
- src/workspaces/features/PipelineVersionsDialog/PipelineVersionsDialog.tsx
Fix redirection issue when running a pipeline due to pipeline version deletion.
- Reload page when deleting a n
- Remove reload on pipeline key changes.
Check that creating a new run redirect to the run details page.
> fix(Pipelines): fix issue with redirection on pipeline run

- src/core/helpers/__tests__/array.test.ts
- src/core/helpers/array.ts
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
Fix 2 issues with pipelines parameters ; one on pipeline run dialog and one on run details page
- ensureArray(value) return now an array of  value instead of an array of size value (when value is a int/float)
- Remove duplicate displayed on pipeline run details
> fix(Pipelines): fix issues with parameters

- src/workspaces/features/RunPipelineDialog/ParameterField.tsx
Add missing validation to pipeline parameters.
- Set required property on select and text area
> feat(Pipelines): validate pipeline parameters

- schema.graphql
- src/graphql-types.ts
- src/workspaces/helpers/connection.tsx
Add IASO connection type.
- Add a form for IASO connection type
> feat(Connections):add IASO connection type

- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
If there is a select in the PipelineRunDialog form, I can edit the select, delete the initial value and click on Run.The field will not be validated.
- Add validate function on PipelineRunDialog useForm
> fix(Pipelines): validate form data before submit

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
- src/workspaces/features/DatabaseTableDataGrid/DatabaseTableDataGrid.generated.tsx
- src/workspaces/features/DatabaseTableDataGrid/DatabaseTableDataGrid.tsx
The Datagrid that display the rows of a table was loaded on the client. This caused the table to disappear/appear quickly.
I've changed the component to be able to prefetch the data on the server
https://github.com/BLSQ/openhexa-frontend/assets/1607549/c9e6d019-141f-41fb-9e60-bbb0b4fe2ab7
> Fix flicker table

- src/workspaces/features/RunPipelineDialog/ParameterField.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
Fix for [issue](https://github.com/BLSQ/openhexa-team/issues/439).
- Set isTouched=false when initializing form
- Check if param is multiple for input with array value
- Do no show error when param type is boolean
[Screencast from 21.06.2023 09:41:22.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/ebba4ad8-58d9-47ea-9127-950e49c0ac65)
> fix(Pipelines): display error only after when a form field is edited

- src/pages/workspaces/[workspaceSlug]/connections/index.tsx
> fix(Connections): Remove the badge on the card and display it as a subtitle

- package-lock.json
- package.json
- src/collections/features/CreateCollectionDialog/CreateCollectionDialog.tsx
- src/collections/features/ManageCollectionItemDialog.tsx
- src/core/components/DataCard/FormSection.tsx
- src/core/components/Dialog.tsx
- src/core/helpers/apollo.ts
- src/core/hooks/__tests__/useForm.ts
- src/core/hooks/useForm.ts
- src/graphql-types.ts
- src/identity/__tests__/__snapshots__/login.test.tsx.snap
- src/identity/__tests__/login.test.tsx
- src/pages/login.tsx
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
- src/pipelines/features/PipelineRunForm/GenericForm.tsx
- src/pipelines/features/PipelineRunForm/IHPForm.tsx
- src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
- src/workspaces/features/CreateWorkspaceDialog/CreateWorkspaceDialog.tsx
- src/workspaces/features/InviteMemberDialog/InviteMemberDialog.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
- src/workspaces/features/UpdateDescriptionDialog/UpdateDescriptionDialog.test.tsx
- src/workspaces/features/UpdateDescriptionDialog/UpdateDescriptionDialog.tsx
- src/workspaces/features/WorkspaceMembers/UpdateWorkspaceMemberDialog/UpdateWorkspaceMemberDialog.tsx
- src/workspaces/helpers/pipelines.generated.tsx
- src/workspaces/helpers/pipelines.ts
Multiple fixes for the pipelines & the useForm hook
- Add a z-index on the backdrop to avoid to display the dialog under it
- Handle the update of the Apollo cache when creating a new run to add it where we want it
- Clean unused `validate` prop on FormSection 
- Clear the Apollo cache after mutations
Basically all the forms need to be tested (I tested some of them such as login, run a pipeline, edit a pipeline...)
> Pipelines fixes

- src/core/components/DataCard/FormSection.tsx
- src/core/helpers/apollo.ts
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
- src/workspaces/features/WorkspaceMembers/DeleteWorkspaceMemberDialog/DeleteWorkspaceMemberDialog.tsx
- src/workspaces/helpers/pipelines.generated.tsx
- src/workspaces/helpers/pipelines.ts
> Pipelines-fixes

- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
> fix: Uncomment runs block on the pipeline page

- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
Display correct trigger mode for run list.
- fix typo on trigger mode
Create multiple runs (scheduled, manual) and check if the trigger mode for each run is correcty displayed on the run list.
> fix(Pipelines): display correct trigger mode

- src/core/helpers/apollo.ts
- src/identity/features/DisableTwoFactorDialog/DisableTwoFactorDialog.tsx
- src/identity/features/EnableTwoFactorDialog/EnableTwoFactorDialog.tsx
- src/workspaces/features/ArchiveWorkspaceDialog/ArchiveWorkspaceDialog.tsx
- src/workspaces/features/ConnectionFieldDialog/ConnectionFieldDialog.tsx
- src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
- src/workspaces/features/CreatePipelineDialog/CreatePipelineDialog.tsx
- src/workspaces/features/CreateWorkspaceDialog/CreateWorkspaceDialog.tsx
- src/workspaces/features/GenerateDatabasePasswordDialog/GenerateDatabasePasswordDialog.tsx
- src/workspaces/features/InviteMemberDialog/InviteMemberDialog.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
- src/workspaces/features/UpdateDescriptionDialog/UpdateDescriptionDialog.tsx
- src/workspaces/features/UploadObjectDialog/UploadObjectDialog.tsx
- src/workspaces/features/WorkspaceMembers/DeleteWorkspaceMemberDialog/DeleteWorkspaceMemberDialog.tsx
- src/workspaces/features/WorkspaceMembers/UpdateWorkspaceMemberDialog/UpdateWorkspaceMemberDialog.tsx
Reset the form state when opening the modal instead of when closing the modal.
- Prevent pipelineRunDialog from changing version when closing modal.
- Set type="submit" on cancel button for ConnectionFieldDialog
> fix(Modals): prevent glitch when closing modal

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/pages/workspaces/[workspaceSlug]/connections/[connectionId].tsx
Remove connection badge from connection details page.
- Change 1
- Change 2
> refacto(Connections): remove connection badge from connection details

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/pages/workspaces/[workspaceSlug]/connections/index.tsx
- src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
- src/workspaces/features/UpdateConnectionFieldsDialog/UpdateConnectionFieldsDialog.tsx
- src/workspaces/graphql/queries.generated.tsx
- src/workspaces/graphql/queries.graphql
- src/workspaces/helpers/connections/custom.tsx
It takes some place in the dialog and it does not allow a lot of fields to be displayed.
> Do not display error element in connections dialog

- public/locales/en/messages.json
- public/locales/fr/messages.json
- schema.graphql
- src/core/components/ErrorBoundary/ErrorBoundary.tsx
- src/core/components/Popover/Popover.tsx
- src/core/components/Switch/Switch.tsx
- src/graphql-types.ts
- src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx
- src/workspaces/features/BucketExplorer/BucketExplorer.tsx
- src/workspaces/graphql/queries.generated.tsx
- src/workspaces/graphql/queries.graphql
Linked to backend PR : https://github.com/BLSQ/openhexa-app/pull/517
It adds a menu on the /files of every workspace to toggle the visibility of the hidden files / folders.
By default they are hidden. By toggling it, they will be visible for every workspace.
> feat(Files): Show/hide hidden files & directories

- src/core/components/DataGrid/DataGrid.tsx
- src/core/components/Overflow/Overflow.tsx
- src/core/components/Overflow/index.ts
- src/dashboards/__tests__/__snapshots__/dashboard.test.tsx.snap
- src/pages/workspaces/[workspaceSlug]/index.tsx
- src/visualizations/__tests__/__snapshots__/visualizations.test.tsx.snap
- src/workspaces/layouts/WorkspaceLayout/WorkspaceLayout.tsx
Creates a visual indicator that the block can be scrolled (x & y).
The behavior has been added to the DataGrid
https://bluesquare.slack.com/files/U029L107EGJ/F05MQ48RE90/cleanshot_2023-08-14_at_17.20.17.mp4
> Implement a Overflow component to display a gradient when there is an overflow

- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
Fix broken breadcrumbs link on pipeline run page.
> fix(Pipelines): fix broken link in breadcrumbs

- src/core/components/Dialog.tsx
- src/core/components/Overflow/Overflow.tsx
- src/dashboards/__tests__/__snapshots__/dashboard.test.tsx.snap
- src/visualizations/__tests__/__snapshots__/visualizations.test.tsx.snap
- src/workspaces/features/CreateBucketFolderDialog/CreateBucketFolderDialog.tsx
- src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
- src/workspaces/features/CreateWorkspaceDialog/CreateWorkspaceDialog.tsx
- src/workspaces/features/InviteMemberDialog/InviteMemberDialog.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
- src/workspaces/features/UpdateConnectionFieldsDialog/UpdateConnectionFieldsDialog.tsx
- src/workspaces/features/UpdateDescriptionDialog/UpdateDescriptionDialog.tsx
- src/workspaces/features/UploadObjectDialog/UploadObjectDialog.tsx
- src/workspaces/features/WorkspaceMembers/UpdateWorkspaceMemberDialog/UpdateWorkspaceMemberDialog.tsx
It fixes the RunPipelineDialog when there are a lot of parameters
Test with a long list of parameters
https://github.com/BLSQ/openhexa-frontend/assets/1607549/1e54b7db-f0db-49f1-a743-bd7db2746767
> fix(Dialog): Make the dialog's content scrollable

- src/pages/workspaces/[workspaceSlug]/connections/index.tsx
[Connections help fine tuning](https://github.com/BLSQ/openhexa-team/issues/495).
- Remove "Using connections in notebooks" and "Using connections in pipelines" sections.
> docs : help fine tuning

- src/core/helpers/page.ts
- src/core/layouts/back/BackLayout.tsx
- src/core/layouts/back/index.ts
- src/identity/graphql/queries.generated.tsx
- src/identity/graphql/queries.graphql
- src/pages/user/account.tsx
The page was not accessible to non legacy users
With a legacy user, go to account page.
With a workspace user, go to account page.
> Fix account page

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/pages/workspaces/[workspaceSlug]/connections/index.tsx
- src/workspaces/features/CreateConnectionDialog/CreateConnectionDialog.tsx
- src/workspaces/features/UpdateConnectionFieldsDialog/UpdateConnectionFieldsDialog.tsx
Revert changes on help modal.
- Revert deleted links on global help modal
- Delete using connections on connection creation modal.
> fix(Connections): revert changes on doc links

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
Update text for schedule section.
> styles(Pipelines): change text for unschedulable pipeline

- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
Fix display of float parameters (multiple) on run page.
> fix(Pipelines): Fix multiple float parameters display

- README.md
Nothing special, simplify and align the first part of the README file with openhexa-app, and a few typo fixes.
> doc: align intro with openhexa-app + typos

- src/workspaces/helpers/connections/s3.tsx
Hide secret values in S3 connection.
[Screencast from 11-22-2023 01:41:45 PM.webm](https://github.com/BLSQ/openhexa-frontend/assets/25453621/80814469-4364-4696-a63d-3d90584d5c2f)
> fix(Connections): hide s3 connection secret key

- jest.setup.js
- src/core/components/MarkdownViewer/MarkdownViewer.tsx
- src/pipelines/features/RunMessages/RunMessages.tsx
Improve pipeline messages UX
- Render url in run message as link 
- Improve multi-line display
> feat(Pipelines): improve pipeline messages UX

- src/workspaces/features/WorkspaceMembers/WorkspaceMembers.tsx
https://github.com/BLSQ/openhexa-team/issues/640
> feat(Workspaces): increase workspace members page size to 10

- src/core/components/Overflow/Overflow.tsx
The bottom was still blurred even when the component was scrolled to the bottom
https://github.com/BLSQ/openhexa-frontend/assets/1607549/8237f471-d8ef-4667-989a-2c9a0a35734f
> fix(Overflow): Fix overflow in vertical mode

- src/core/layouts/default/Header.tsx
- src/core/layouts/default/__tests__/Header.test.tsx
- src/core/layouts/default/__tests__/__snapshots__/Layout.test.tsx.snap
Nothing special, just commenting the quick search component so that all search features are "hidden".
> chore: disable search for now

- schema.graphql
- src/graphql-types.ts
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
- Clearly differentiate a pipeline run created by a webhook.
- Fix a bug in the display of the parameters in the run page
> fix(Pipelines): Add a 'Webhook' run trigger & Improve parameters display

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/core/hooks/useAutoScroll.ts
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
- src/pipelines/features/PipelineRunStatusBadge.tsx
- src/pipelines/features/RunMessages/RunMessages.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
* Increase polling
* Remove the overflow indicator for messages
* Change the design of the message list
https://github.com/BLSQ/openhexa-frontend/assets/1607549/31d8f3a0-6ef4-4ce8-9266-02d14df023c2
> Improve run messages

- src/identity/helpers/auth.test.tsx
- src/identity/helpers/auth.ts
- src/workspaces/features/SidebarMenu/SidebarMenu.tsx
> fix: use POST request for logout

- README.md
A bit of stylistic changes and a few adaptations for the local dev part.
> README fine-tuning

- .github/workflows/ci.yml
- README.md
- package.json
- scripts/validate-i18n.mjs
Updates the GitHub action CI to validate that all the strings are translated (for all languages enabled on the platform)
Example: https://github.com/BLSQ/openhexa-frontend/actions/runs/7488216980/job/20382208399
> chore(i18n): Validate that all strings are translated

- src/pages/workspaces/[workspaceSlug]/files/[[...prefix]].tsx
I suspect the next router to behave differently than on other browsers
> fix(Files): search was not working on Chrome (weird bug on thie browser)

- next-env.d.ts
- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/datasets/features/DatasetPicker/DatasetPicker.generated.tsx
- src/datasets/features/DatasetPicker/DatasetPicker.test.tsx
- src/datasets/features/DatasetPicker/DatasetPicker.tsx
- src/datasets/features/DatasetPicker/__snapshots__/DatasetPicker.test.tsx.snap
- src/datasets/features/DatasetPicker/index.tsx
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
- src/workspaces/features/RunPipelineDialog/ParameterField.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
Allow user to select dataset when running a pipeline.
- Add DatasetPicker component to RunPipelineDialog
> feat(Pipeline):add support for dataset parameter

- Dockerfile
- next-env.d.ts
- package-lock.json
- package.json
- src/core/components/CodeEditor/CodeEditor.tsx
Drawback: We had to remove the R language for codemirror (for now at least)
> chore: update dockerfile to use node 20

- src/datasets/features/UploadDatasetVersionDialog/UploadDatasetVersionDialog.tsx
> fix(Datasets): Fix the example snippet on how to use the sdk to create a version

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/core/components/Alert.tsx
- src/core/components/AlertManager/AlertManager.tsx
- src/core/helpers/alert.ts
- src/identity/features/DisableTwoFactorDialog/DisableTwoFactorDialog.tsx
- src/identity/features/EnableTwoFactorDialog/EnableTwoFactorDialog.tsx
- src/pages/login.tsx
- src/pages/workspaces/[workspaceSlug]/notebooks.tsx
- src/pages/workspaces/index.tsx
- src/workspaces/features/RunPipelineDialog/RunPipelineDialog.tsx
- Added a new type of alert "success"
- Display an alert when the user asks for a new 2FA code
- Fix the space between the inputs and the error
> fix(Login): fix error spacing; Add an alert when user asks for a new code

- README.md
- src/pages/_document.tsx
We would like to have small insights on our users for the web application.
> chore(Telemetry): Telemetry can be enabled with the env variable 'TELEMETRY_ID'

- public/locales/en/messages.json
- public/locales/fr/messages.json
- src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
- src/workspaces/features/DeletePipelineDialog/DeletePipelineDialog.generated.tsx
- src/workspaces/features/DeletePipelineDialog/DeletePipelineDialog.test.tsx
- src/workspaces/features/DeletePipelineDialog/DeletePipelineDialog.tsx
- src/workspaces/features/DeletePipelineDialog/__snapshots__/DeletePipelineDialog.test.tsx.snap
- src/workspaces/features/DeletePipelineDialog/index.tsx
- src/workspaces/graphql/mutations.generated.tsx
- src/workspaces/graphql/mutations.graphql
- src/workspaces/graphql/queries.generated.tsx
- src/workspaces/graphql/queries.graphql
Allow user to delete pipelines if it has the permission.
- Add DeletePipelineDialog component
- Add a Delete button on Pipeline details view.
> feat(Pipelines): allow user to delete pipeline

- schema.graphql
- src/graphql-types.ts
- src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
- src/workspaces/features/DeleteDatabaseTableTrigger/DeleteDatabaseTableTrigger.generated.tsx
- src/workspaces/features/DeleteDatabaseTableTrigger/DeleteDatabaseTableTrigger.test.tsx
- src/workspaces/features/DeleteDatabaseTableTrigger/DeleteDatabaseTableTrigger.tsx
- src/workspaces/features/DeleteDatabaseTableTrigger/index.tsx
- src/workspaces/graphql/queries.generated.tsx
- src/workspaces/graphql/queries.graphql
- src/workspaces/helpers/database.generated.tsx
- src/workspaces/helpers/database.tsx
https://github.com/BLSQ/openhexa-frontend/assets/25453621/a9306147-454f-4cbf-89e4-4f09e708a610
> feat(Databases): allow admin/editor to delete table

- src/middleware.ts
The logout doesn't work anymore in demo. This PR intends to fix by adding a handler for the logout endpoint.
- Add logout endpoint to middleware matchers.
> fix(Next): handle logout url in middleware

- src/pages/register.tsx
- src/workspaces/features/PipelineVersionConfigDialog/PipelineVersionConfigDialog.tsx
When there are a lot of parameters, it was not possible to scroll the dialog.
> Fix pipelines config dialog

- src/core/helpers/analytics.ts
- src/middleware.ts
- src/pages/workspaces/[workspaceSlug]/databases/[tableId].tsx
- src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug].tsx
Track events and viewed page from the front-end.
- Add dataset_version and table_viewed events
-  Track viewed page
> feat(Analytics): track events  and viewed page

- src/workspaces/features/RunPipelineDialog/ParameterField.test.tsx
- src/workspaces/features/RunPipelineDialog/ParameterField.tsx
Fix for JP [bug](https://bluesquare.slack.com/archives/C0288HL2P7C/p1721828831720259) 
Current bug:
https://github.com/user-attachments/assets/ccafccfd-bc5b-406c-b50a-eeebd7a2dbb5
Fixed : 
https://github.com/user-attachments/assets/9bf6da47-79f0-49af-bf8d-c81e16a78cb0
> fix(Pipelines): set default value as array for multi choices param

- src/middleware.ts
Add new endpoints to forward to the backend
> chore(localhosting): Add /files to middleware bypass

- Dockerfile
- README.md
- src/core/helpers/analytics.ts
Add `DISABLE_ANALYTICS` to avoid to send a request to the backend when we want to forcefully disable the analytics.
> chore(Analytics): Refactor the two function to use one helper and add a flag to disable analytics

- schema.graphql
- src/graphql/types.ts
- src/identity/graphql/queries.generated.tsx
- src/identity/graphql/queries.graphql
- src/pages/register.tsx
Display django password requirements
> fix(Account): display password requirements on register

- src/pages/user/account.tsx
See [issue](https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/330?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-1002)
> feat(Account): Switch action buttons position

- package-lock.json
- package.json
- server/index.mjs
- src/datasets/features/UploadDatasetVersionDialog/UploadDatasetVersionDialog.tsx
> Fix dataset version

- src/datasets/features/DatasetVersionFileSample/DatasetVersionFileSample.tsx
This is for an experimental feature. We now set a explicit height.
> fix(datasets): Give a specific height to the <embed /> to preview the pdfs

- src/workspaces/features/CreatePipelineDialog/CreatePipelineDialog.tsx
Show the button in the correct tab and ensure the form is submitting
Pipeline dialog
> fix: Create pipeline dialog is not showing the create button

- jest.setup.js
- package-lock.json
- package.json
- src/core/components/DataCard/TextProperty.tsx
- src/core/components/MarkdownEditor/MarkdownEditor.tsx
- src/core/components/MarkdownViewer/MarkdownViewer.tsx
- src/pages/pipelines/[pipelineId]/run.tsx
- src/pages/workspaces/[workspaceSlug]/index.tsx
- src/pipelines/features/UpgradePipelineFromTemplateDialog/UpgradePipelineFromTemplateDialog.tsx
Fix glitches with markdowns and support images in markdowns 
- Plugin for images
- Close editing when changing workspaces and sync the description
Editing markdowns with images and/while changing workspaces
> fix: glitches with markdowns and support images in markdowns (HEXA-1194)

- server/index.mjs
See linked PR in blsq/openhexa-app#931
Just proxy /superset urls to the backend...
> chore(superset): Proxy /superset urls to openhexa-app
